### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [deshario/web-scraper#24]
Hello @deshario  👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
I have completed the first round of review. I focused on the core issue that I think can be tackled in the short time we have :-). There are other areas of improvement, such as increasing the test coverage for the scraper, but let's focus on the 6 issues for now.

Looking forward to your feedback on the open issue.

**Comment by deshario** [comment]
Hi @olivierobert  👋

Thanks for the feedback and am ready to address those six core issues you've identified.

If I have any concerns/questions about those issues, I'll be sure to let you know.

**Comment by olivierobert** [comment]
@deshario It would be best to make all changes in a pull request and keep those open. It would simplify the code review process on my side. Once reviewed and approved, you could merge the changes.

**Comment by deshario** [comment]
@olivierobert Sure,

I've already merged two pull request before

But, I will wait for a review for the next pull request.

Please feel free to review the PR that was mentioned in the issue

Thanks

**Comment by olivierobert** [comment]
I have reviewed the code changes and added some comments. Please review these, and upon receiving your response we will be able to close this stage of the recruitment process ✌️

**Comment by deshario** [comment]
Hi,

I appreciate your review 🙏

Based on recent comments, I've made some updates to the existing pull request and merged the approved one.

Thanks

**Comment by olivierobert** [comment]
I have completed the last round of reviews. This stage of the recruitment is thus completed.

Our team will reach out to you shortly by email to share our feedback.

Thank you for your efforts 💪
