### ISSUE TITLE
[Feature] Separate each keyword to its own background job

### ISSUE THREAD

**Issue by olivierobert** [deshario/web-scraper#25]
## Issue

The keywords are queued in chunks of 5:

https://github.com/deshario/web-scraper/blob/1ed655da633c6ec2e3f8ce7a5184b0abd2ea3750/apps/server/src/api/keywords/controller.ts#L37-L44

Then processed in a loop:

https://github.com/deshario/web-scraper/blob/1ed655da633c6ec2e3f8ce7a5184b0abd2ea3750/apps/server/src/services/scraper/processor.ts#L46-L58

This approach has some drawbacks:
- If any error occurs for one of the keywords, the whole chunk will error out
- Added Complexity in managing random delays between the processing of each keyword
- No granular observability 

## Expected

It is best to queue each keyword individually as it presents the following benefits:
- Random delay calculation can be managed at the enqueuing step (i.e., instead of being fixed, it can be randomly calculated) avoid using setTimeout (which is not accurate anyway 😉 ).

https://github.com/deshario/web-scraper/blob/1ed655da633c6ec2e3f8ce7a5184b0abd2ea3750/apps/server/src/services/scraper/queue.ts#L13

- Failure for one keyword will not affect other keywords
- Granular update to the UI
- Easier debugging and testing

**Comment by deshario** [comment]
I see, that sounds much better.
