### ISSUE TITLE
[Chore] Swap HTML content from file to database storage

### ISSUE THREAD

**Issue by olivierobert** [deshario/web-scraper#26]
## Issue

The scraped content is stored in files:

https://github.com/deshario/web-scraper/blob/1ed655da633c6ec2e3f8ce7a5184b0abd2ea3750/apps/server/src/services/scraper/processor.ts#L49-L55

<img width="303" alt="image" src="https://github.com/deshario/web-scraper/assets/696529/ba4d0bae-aade-49ee-bab7-3d52d9acf719">

Then this file is used to render a page:

<img width="1033" alt="image" src="https://github.com/deshario/web-scraper/assets/696529/8f63215e-c976-40bc-a8f5-917bc7b984fd">

This approach has significant drawbacks to deploying the application. In most PaaS services such as Heroku, storage is ephemeral 😅 When using a cloud provider such as AWS or GCP, it will require to use a separate Object storage for that purpose.

## Expected

- The HTML content is stored in the database. 
- The HTML is fetched from the database to be displayed

> [!Note]
> While the DB size could be a concern in a real-world application, a separate DB storage could be used for that purpose. For the purpose of this code challenge, the tradeoff of DB storage surpasses the ones for DB storage as we expect candidates to deploy the application if they want/can.

**Comment by deshario** [comment]
My only concern on this was the DB size, which is why I chose not to store large data in it.

However, for the specific challenge, I will store it back in the DB

**Comment by olivierobert** [comment]
Why create a new table instead of adding a new column to the existing table to store keywords? I would like to understand better your technical decision-making process.

**Comment by deshario** [comment]
If we store **large** HTML directly in the main table ... I think there could be a potential query performance issues in the near future as the number of records grows (I haven't clearly tested it yet)

But this is one of the reason why I store HTML content separately in a different table and query only when needed.

**For instance:**
In client's page, we don't immediately display HTML content ... it's only shown upon clicking (when needed)

This approach makes me think about storing it in separate table.


This separation serves:
- Maintain the cleanliness and efficiency of the main keyword table
- Prevent overloading the main keyword table.

However, I'm also open to using the same table if there won't be a significant difference in performance aspects
