### ISSUE TITLE
[Chore] Extract business logic from the Keyword controller

### ISSUE THREAD

**Issue by olivierobert** [deshario/web-scraper#27]
## Issue

<img width="823" alt="image" src="https://github.com/deshario/web-scraper/assets/696529/98f1b1a4-9fd5-4fa3-818a-0a405090c46d">

The API controllers are on the fat side of the spectrum: they contain business logic that could be extracted and more easily tested in services. For instance, the CSV parsing and keyword creation could be in separate services. Controllers should be "dumb" and have only the responsibility to call other objects to do the heavy lifting.

## Expected

Use the existing services directory to create the following services/use cases:
- `services/keyword/parseCsv.ts`
- `services/keyword/createKeyword.ts`

**Comment by deshario** [comment]
I see, will split it out. Thanks
