### ISSUE TITLE
[Feature] Validate the maximum number of keywords for upload

### ISSUE THREAD

**Issue by olivierobert** [deshario/web-scraper#28]
## Issue

The following requirement has not been implemented:

<img width="659" alt="image" src="https://github.com/deshario/web-scraper/assets/696529/4a561155-ee66-4335-b0e6-0e7e1bd95427">

As a result, a user can upload as many keywords as the want, which could lead in breaking the application or having it banned by Google 😱 

## Expected

Implement the required validation in the new CSV parsing logic created in #27

**Comment by deshario** [comment]
Nice catch!

I'll add validation for it. Thanks

**Comment by olivierobert** [comment]
I have added a comment on the PR about not hardcoding the value

**Comment by deshario** [comment]
I've pushed the changes for it. Thanks
