### ISSUE TITLE
[Chore] Improve error handling

### ISSUE THREAD

**Issue by olivierobert** [deshario/web-scraper#29]
## Issues

Error handling is sometimes not sufficiently well thought out:
- https://github.com/deshario/web-scraper/blob/main/apps/server/src/services/scraper/processor.ts#L36 
- https://github.com/deshario/web-scraper/blob/main/apps/server/src/services/scraper/scraper.ts#L14. 
 
In other cases, error are only consoled out.

## Expected

It would be best to `throw` errors:

```
if (file.type !== 'text/csv') {
  throw new Error('The file is of the incorrect expected type (CSV)');
}
``` 

Or even custom errors:

```
if (!credentials) {
  throw new AuthError({ message: 'Email and Password must be provided on logging in.' });
}
```

With `AuthError` being defined as:

```
export default class AuthError extends Error {}
```

**Comment by deshario** [comment]
Sure thing!
