### ISSUE TITLE
[Feature] Change color of non-error notifications

### ISSUE THREAD

**Issue by olivierobert** [deshario/web-scraper#30]
## Issue

Non-error notifications are shown in red:

<img width="538" alt="Screenshot 2566-09-28 at 05 35 20" src="https://github.com/deshario/web-scraper/assets/696529/d7eec6a6-2845-44a8-ae88-aa7fb0173415">

As a user, it can give the impression of something went wrong 😱 

## Expected

Revisit the UI to make such message user-friendly. Optionally, think of moving notifications at the app level so that they can be used outside of the `useAuth` hook 💡

**Comment by deshario** [comment]
It was overlooked due to time limitations.

But I'll make sure to handle notifications properly

Thanks
